version: "3.3"
services:
  web:
    ports:
      - "5000:5000"
    image: "kkogaa/chatbot-service"
    environment:
      - PORT=5000
      - EUREKA_URL=http://ec2-50-16-212-46.compute-1.amazonaws.com:8761/eureka/
      - HOST_PUBLIC_IP=54.163.36.214
      - DB_URL=db-maynardcode.cm7jvq9vp9i9.us-east-1.rds.amazonaws.com:3306/maynardcode
      - DB_USER=admin
      - DB_PASSWORD=pucppassword123
